Create a function scalar_multiply(c, v) where c is a scalar and v is a vector. The function should return a new vector where each element is c times the corresponding element in v.

In [14]:
import numpy as np
def scalarmult(c,v):
  return np.array([c*x for x in v])


v=np.array([1,2,3])
a=5
print(scalarmult(a,v))

[ 5 10 15]


Using NumPy, add two vectors v1 and v2.

In [2]:
import numpy as np
def add_vectors(v1, v2):
  return np.add(v1, v2)

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(add_vectors(v1, v2))


[5 7 9]


Perform scalar multiplication of a vector using NumPy.

In [3]:
import numpy as np
v=np.array([1,2,3])
a=5
print(scalarmult(a,v))

[ 5 10 15]


Multiply two matrices using NumPy.

In [15]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(np.matmul(a,b))

#or use that : C = a @ b

[[ 7 10]
 [15 22]]


Multiply the matrices using dot product

In [20]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.dot(a, b)

print(c)

[[19 22]
 [43 50]]


In [17]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
C = a @ b
print(C)

[[ 7 10]
 [15 22]]


Compute the transpose of a matrix using NumPy.

In [23]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.transpose(a)
print(b)

[[1 3]
 [2 4]]


or that version :

In [33]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [34]:
a_transpose = a.T
print(a_transpose)

[[1 4]
 [2 5]
 [3 6]]


reshape

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.shape(a)

(2, 3)

In [37]:
b=a.reshape(3,2)

In [38]:
np.shape(b)

(3, 2)

In [39]:
b.reshape(6)

array([1, 2, 3, 4, 5, 6])

Matrix inverse and indentity matrix

In [40]:
import numpy as np
# Compute the inverse of a matrix using NumPy.
a = np.array([[1, 2], [3, 4]])
b = np.linalg.inv(a)
print(b)

# Compute the identity matrix using NumPy.
identity_matrix = np.eye(3)
print(identity_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
