#Numpy Notebook 
Notes from Patika.dev and Linkedin Lynda
###Lala Ibadullayeva


NumPy 
- Arithmetic operations
- Statistics operations
- Bitwise operations
- Copying and viewing array
- Stacking
- Matrix operations
- Broadcasting
- Linear Algebra
- Mathematical operations
- Searching, sorting, counting


In [1]:
import numpy as np

creating arrays from lists

In [2]:
x=np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
type(x)

numpy.ndarray

creating arrays from strings

In [5]:
y=np.array(["a","b","c"])

In [6]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
z=np.array([1,2,3,"a"])

In [8]:
z

array(['1', '2', '3', 'a'], dtype='<U21')

both float and integer

In [9]:
b=np.array([1,2,3,4.5])

In [10]:
b

array([1. , 2. , 3. , 4.5])

In [11]:
type(b)

numpy.ndarray

float, strings and integers in the same line

In [12]:
c=np.array([1,2,3,4.5,"2"])

In [13]:
c

array(['1', '2', '3', '4.5', '2'], dtype='<U32')

manually specifying the array data type

In [14]:
x=np.array([1,2,3,4.6])

In [15]:
x

array([1. , 2. , 3. , 4.6])

In [16]:
x=np.array([1,2,3,4.6], dtype = "int32")

In [17]:
x

array([1, 2, 3, 4], dtype=int32)

In [18]:
x=np.array([1,2,3,4.5], dtype = "str")

In [19]:
x

array(['1', '2', '3', '4.5'], dtype='<U3')

In [20]:
x=np.array(["a"],dtype="int32")

ValueError: ignored

In [ ]:
x=np.array(["5"],dtype="int32")

In [ ]:
x

In [ ]:
x=np.array(["4.5"],dtype="int32")  #interesting

Zero to Array

In [ ]:
np.zeros(10)

In [ ]:
type(np.zeros(10))

In [ ]:
np.zeros(10, dtype= "int32")

In [ ]:
np.zeros(10,dtype=str)

In [ ]:
np.zeros(10,dtype="str") #interesting

In [ ]:
np.zeros((3,4))

In [ ]:
np.zeros((3,4), dtype= "int32")

In [ ]:
np.zeros(3,4)
#We need a data type

In [ ]:
np.zeros([3,4])

In [ ]:
np.zeros([3,8,8])

In [ ]:
np.zeros(2, dtype = int)

In [ ]:
np.zeros((1,2), dtype=str)

In [ ]:
np.zeros((2,3), dtype=bool)

Full function

In [ ]:
np.full((2,3), fill_value=1, dtype =bool)

In [ ]:
np.full((4,5),5)

In [ ]:
np.full(3,4)

In [ ]:
np.full((3,4))
#we need a fill value

In [ ]:
np.zeros((3,4))
#comparison

In [ ]:
np.full((4,5),"a")

In [ ]:
np.full((4,5),"5.2")

In [21]:
np.full((4,5), 5.2, dtype= "str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

Arange function

In [22]:
#[0,12)
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [24]:
np.arange(2,12,-2)

array([], dtype=int64)

In [25]:
np.arange (12,2,-2)

array([12, 10,  8,  6,  4])

linspace function

In [26]:
#default 50 point
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [27]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [28]:
np.linspace(1,2,num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [29]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [30]:
np.linspace(1.5,4.7,3)

array([1.5, 3.1, 4.7])

Random function

In [31]:
#(mean,std,arraysize)
np.random.normal(0,1,(4,5))

array([[-2.48089919, -1.16790943, -2.94016967, -1.77663095, -1.98431195],
       [-1.16337213, -1.36274109, -0.59950837, -2.73685802,  1.42277048],
       [ 0.69269008,  0.86233312,  0.08174286,  1.54990397,  0.92377753],
       [ 0.54199208, -0.9709444 ,  2.26723166, -0.87542257,  0.73515673]])

In [32]:
np.random.normal(0,100,(4,5))

array([[  88.06719754, -298.71510779,   43.48743338,  109.86508786,
         -21.49230569],
       [-118.13561647,   75.96492066,  -18.19552924, -211.63643388,
          30.08344629],
       [  38.61812729,  -47.42137354,  215.74923864,  162.21138375,
         143.23837999],
       [ -72.35658543,  -24.58733482,   63.23074681,   29.84065969,
         168.25304662]])

In [33]:
#[low, high)
np.random.randint(1,10,(3,4))

array([[3, 5, 3, 7],
       [3, 5, 8, 2],
       [3, 9, 2, 1]])

In [34]:
np.random.randint(1,10,(3,5,5))

array([[[3, 6, 7, 3, 6],
        [6, 6, 7, 7, 4],
        [6, 4, 5, 6, 5],
        [9, 7, 1, 3, 1],
        [2, 1, 1, 8, 4]],

       [[7, 4, 6, 9, 7],
        [2, 5, 5, 6, 4],
        [2, 2, 9, 3, 1],
        [8, 9, 1, 8, 8],
        [1, 3, 4, 8, 1]],

       [[9, 4, 4, 6, 6],
        [3, 9, 6, 6, 5],
        [3, 6, 1, 6, 9],
        [1, 4, 1, 2, 7],
        [9, 2, 3, 7, 3]]])

In [35]:
np.random.randint(1,2)

1

In [36]:
np.random.randint(1,3)

1

In [37]:
np.random.normal(1,10,(3,4)) #float type

array([[ 11.25610366,  26.18644539,  -1.70909101,  10.85732226],
       [  5.43748199, -24.53929622,   8.01946699,  -6.31699254],
       [ 10.34066219,  -2.85420953,  -7.99164164,  -5.01348138]])

Identity Matrix

In [38]:
#identity matrix
#[low, high)
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
#dioganal design
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array operations

In [40]:
a=[1,2,3]
b=[2,4,8]
a*b

TypeError: ignored

In [41]:
b*3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [42]:
b+b+b

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [43]:
x=np.array([1,2,3])
y=np.array([2,4,8])
x*y

array([ 2,  8, 24])

In [44]:
#Note : element-wise multiplication
x2=np.array([1,2,3])
y2=np.array([2,4,8,10])
x2*y2

ValueError: ignored

In [ ]:
#concatenation
a=[1,2,3]
b=[2,4,8]
a+b

In [45]:
print(x)
print(y)
x+y

[1 2 3]
[2 4 8]


array([ 3,  6, 11])

In [46]:
a

[1, 2, 3]

In [47]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [48]:
x

array([1, 2, 3])

In [49]:
3*x

array([3, 6, 9])

In [50]:
x

array([1, 2, 3])

In [51]:
x=x*3

In [52]:
x

array([3, 6, 9])

In [53]:
np.array([3,5,9]) * 3

array([ 9, 15, 27])

Array attribute

In [54]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
y=np.zeros((2,5,4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [56]:
x.shape

(2, 3)

In [57]:
y.shape

(2, 5, 4)

In [58]:
x.ndim

2

In [59]:
y.ndim

3

In [60]:
x.size

6

In [61]:
y.size

40

In [62]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [63]:
x.dtype

dtype('float64')

Reshaping

In [64]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
a.ndim

1

In [66]:
a.size

10

In [67]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [69]:
b=a.reshape(2,5)

In [70]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
b.reshape(2,5).ndim

2

In [72]:
b.reshape(6,2)
#If the element does not count, it throws an error.

ValueError: ignored

In [73]:
a.reshape(-1,2)
#it calculates itself.

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [74]:
a=np.arange(1,11)

In [75]:
a[np.newaxis,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [76]:
a[np.newaxis,:].shape

(1, 10)

In [77]:
a[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [78]:
a[:,np.newaxis].shape

(10, 1)

In [79]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [80]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

Concatenation

In [82]:
a= np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [83]:
a

array([1, 2, 3, 4])

In [84]:
b

array([5, 6, 7, 8])

In [85]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
l=([10,11])

In [87]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [88]:
l=([10,11,11.2])

In [89]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [90]:
l=([10,11,"11.2"])

In [91]:
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U21')

In [92]:
l2=(10,11)

In [93]:
np.concatenate([a,b,l2])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

Size mismatch

In [94]:
a

array([1, 2, 3, 4])

In [114]:
x=np.concatenate([[1,2,3],
                  [4,5,6]])

In [115]:
x

array([1, 2, 3, 4, 5, 6])

In [116]:
x.size

6

In [117]:
x.shape

(6,)

In [118]:
a.shape

(4,)

In [119]:
np.concatenate([x,a])
#It did not return an error because it was a new version of Python.

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4])

In [120]:
np.concatenate([x,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [121]:
np.concatenate([x,x],axis=0)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

Stack

In [123]:
a=np.array([1,2,3,4])

In [124]:
a

array([1, 2, 3, 4])

In [125]:
b=np.array([5,6,7,8])

In [126]:
b

array([5, 6, 7, 8])

In [127]:
a.shape

(4,)

In [128]:
b.shape

(4,)

In [130]:
np.stack([a,b],axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
np.stack([a,b],axis=0).shape

(2, 4)

In [132]:
np.stack([a,b],axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [133]:
np.stack([a,b],axis=1).shape

(4, 2)

Split

In [134]:
l=[10,20,30,40,50,60,70,80]

In [135]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [136]:
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [137]:
np.split(l,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [138]:
a=np.array([10,20,30,40,50,60,70,80])

In [139]:
np.split(a,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [140]:
type(np.split(a,[2,6]))

list

Comparison the codes

In [141]:
a,b=(1,10)
print(a)
print(b)

1
10


In [142]:
x,y,z=np.split(l,[2,6])
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


Vertical Split - VSplit

In [146]:
a=np.arange(20).reshape(2,10)

In [147]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [149]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [150]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Horizontal Split -hsplit

In [151]:
a=np.arange(20).reshape(2,10)

In [152]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [153]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]), array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [154]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [155]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [156]:
np.hsplit(a,[2])[0].shape

(2, 2)

In [157]:
np.hsplit(a,[2])[1].shape

(2, 8)

In [158]:
x,y=np.hsplit(a,[2])
print(x)
print(y)

[[ 0  1]
 [10 11]]
[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [160]:
x,y,z=np.hsplit(a,[2,4])
print(x)
print(y)
print(z)

[[ 0  1]
 [10 11]]
[[ 2  3]
 [12 13]]
[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


In vertical Split

In [161]:
a=np.arange(20).reshape(5,4)

In [162]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [163]:
np.vsplit(a,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

Sorting

In [164]:
a=np.array([20,32,5,30,10])

In [165]:
a

array([20, 32,  5, 30, 10])

In [166]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [167]:
a

array([20, 32,  5, 30, 10])

In [169]:
a.sort()

In [170]:
a

array([ 5, 10, 20, 30, 32])

argsort

In [171]:
a=np.array([3,1,6,5,4,2])

In [172]:
idxs=np.argsort(a)

In [173]:
idxs

array([1, 5, 0, 4, 3, 2])

Indexing @ Multidimensional Arrays

In [174]:
a=np.arange(1,21).reshape(4,5)

In [175]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [176]:
a[0]

array([1, 2, 3, 4, 5])

In [177]:
a[1]

array([ 6,  7,  8,  9, 10])

In [178]:
a[0,0]

1

In [179]:
a[0][0]

1

In [180]:
a[1,1]

7

In [181]:
a[0,1]

2

In [182]:
a.ndim

2

In [183]:
a[0]

array([1, 2, 3, 4, 5])

In [184]:
a[0].ndim

1

In [185]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [186]:
a[1,1]=10

In [187]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [188]:
a[1,1]=20.40

In [189]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [190]:
a[1,1]="30"

In [191]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [193]:
#Note
a[1,1]="30.5"

ValueError: ignored

In [195]:
#Note
a[1,1]="a"

ValueError: ignored

Slice indexing

In [196]:
a=np.arange(1,21).reshape(4,5)

In [197]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [198]:
a[1]

array([ 6,  7,  8,  9, 10])

In [199]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [200]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [201]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [202]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [203]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [204]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [205]:
a[:,3]

array([ 4,  9, 14, 19])

In [206]:
a[:,3].shape

(4,)

In [207]:
a[::2,3]

array([ 4, 14])

In [208]:
a[0,:]

array([1, 2, 3, 4, 5])

In [209]:
a[0]

array([1, 2, 3, 4, 5])

In [210]:
a[0,2:4]

array([3, 4])

In [211]:
a[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [212]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [213]:
#or
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

Fancy Indexing

In [214]:
x=np.arange(1,15)

In [215]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [216]:
idxs=[4,5,7,11] #Returns the elements in the index

In [217]:
x[idxs]

array([ 5,  6,  8, 12])

In [218]:
idxs=[4,5,7,1]

In [219]:
x[idxs]

array([5, 6, 8, 2])

In [220]:
a=np.arange(12).reshape(3,4)

In [221]:
a[0:2,1]

array([1, 5])

In [222]:
a[0:2,1].shape

(2,)

In [223]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [224]:
a[0:2,1:3].shape

(2, 2)

In [225]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [226]:
a[0,[1,3]]

array([1, 3])

In [227]:
a[0,[1,3]].shape

(2,)

In [228]:
a[0:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

Both parts in fancy indexing

In [229]:
a=np.arange(20).reshape(4,5)

In [230]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [231]:
idx1=[1,3,2]

In [232]:
idx2=[3,0,2]

In [233]:
a[idx1,idx2]

array([ 8, 15, 12])

In [234]:
a[idx1,idx2].shape

(3,)

In [236]:
#Note
a[idx],[idx2]

NameError: ignored

In [237]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [238]:
x[[1,2,3]]=20

In [239]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [240]:
x=np.arange(9)

In [241]:
x[[1,2,5]]=[100,200,300]

In [242]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])

Subarray

In [243]:
a=np.arange(1,21).reshape(4,5)

In [244]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [245]:
b=a[:2,:3]

In [246]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [247]:
b.ndim

2

In [248]:
b[0,0]=100

In [249]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [250]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

Copy()

In [253]:
a=np.arange(1,21).reshape(4,5)

In [254]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [255]:
b=a[:2,:3].copy()

In [256]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [257]:
b[0,0]=100

In [258]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [259]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Filter - Conditional Indexing

In [260]:
a=np.arange(1,10)

In [261]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [262]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [263]:
a[a<5]

array([1, 2, 3, 4])

In [264]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [265]:
filt=a<3

In [266]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [267]:
a[filt]

array([1, 2])

In [268]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [269]:
b=np.array([2,3,3,4,5,61,7,8,11])

In [270]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [271]:
a==b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [272]:
a[a==b]

array([3, 4, 5, 7, 8])

In [273]:
b[a==b]

array([3, 4, 5, 7, 8])

And &, or | 

In [274]:
(a<3) or (a>5)

ValueError: ignored

In [275]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [277]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [278]:
filt=(a<3) | (a>5)

In [279]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [280]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [282]:
a[(a>3)&(a<=5)]

array([4, 5])

In [283]:
#Not function with ~
a=np.arange(1,21).reshape(4,5)

In [284]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [285]:
filt=a<5

In [286]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [287]:
a[filt]

array([1, 2, 3, 4])

In [288]:
filt=(a>5)&(a<9)

In [289]:
a[!(a>5)&(a<9)]

SyntaxError: ignored

In [290]:
a[not(a>5)&(a<9)]

ValueError: ignored

In [291]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [292]:
~((a>5)&(a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Multidimensional arrays in conditional indexing

In [293]:
a=np.arange(1,21).reshape(4,5)

In [294]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [295]:
type(a)

numpy.ndarray

In [297]:
type(a<7)

numpy.ndarray

In [298]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [299]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [301]:
a=np.array([1,2,3,None])

In [302]:
a

array([1, 2, 3, None], dtype=object)

In [303]:
a==None

array([False, False, False,  True])

In [304]:
a[a==None]

array([None], dtype=object)

Sum

In [305]:
a=np.arange(1,21).reshape(4,5)

In [306]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [307]:
np.sum(a)

210

In [308]:
filt=a<5

In [309]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [310]:
np.sum(filt)

4

In [311]:
a[filt]

array([1, 2, 3, 4])

In [312]:
np.sum(filt)

4

In [313]:
a[filt]

array([1, 2, 3, 4])

In [314]:
np.sum(a[filt])

10

In [315]:
filt=(a>5)&(a<9)

In [316]:
np.sum(filt)

3

In [317]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [318]:
a[filt]

array([6, 7, 8])

In [319]:
np.sum(a[(a>5)&(a<9)])

21

In [320]:
filt=~((a>5)&(a<9))

In [321]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [323]:
np.sum(~((a>5)&(a<9)))

17

In [324]:
np.sum(a[~((a>5)&(a<9))])

189

Concatenation with axis[0], axis[1]

In [325]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [326]:
np.sum(a,axis=0)

array([34, 38, 42, 46, 50])

In [327]:
np.sum(a,axis=1)

array([15, 40, 65, 90])

All

In [328]:
a=np.arange(20).reshape(4,5)

In [329]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [330]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [331]:
np.all(a>-1)

True

In [332]:
np.all(a>5)

False

In [333]:
np.all(a>-1,axis=1)

array([ True,  True,  True,  True])

In [334]:
np.all(a>-1,axis=0)

array([ True,  True,  True,  True,  True])

In [336]:
np.all(a>5,axis=1)

array([False, False,  True,  True])

In [337]:
np.all(a>5,axis=1).shape

(4,)

In [338]:
np.all(a>5,axis=1).ndim

1

In [339]:
np.all(a>5,axis=0)

array([False, False, False, False, False])

Any

In [340]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [341]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [342]:
np.any(a>17)

True

In [343]:
np.any(a>17,axis=0)

array([False, False, False,  True,  True])

In [344]:
np.any(a>17,axis=1)

array([False, False, False,  True])

Note :    from Linkedin Lynda  
for integers - "int 32" and "int64"
for floats - "int 64"
If you type "int8" your bytes will be smaller size. But, you`ll meet an overflow.

In [347]:
integers = np.array([21,20,30,40,50])
smallerintegers = np.array(integers,dtype = np.int8)
smallerintegers

array([21, 20, 30, 40, 50], dtype=int8)

In [348]:
integers.nbytes

40

In [349]:
smallerintegers.nbytes

5

In [350]:
overflow=np.array([127,128,129],dtype = np.int8)
overflow

array([ 127, -128, -127], dtype=int8)